//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathOfLeagueStart.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLeagueLaunched {
            get {
                return ((string)(this["LastLeagueLaunched"]));
            }
            set {
                this["LastLeagueLaunched"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GGGClientFilePath {
            get {
                return ((string)(this["GGGClientFilePath"]));
            }
            set {
                this["GGGClientFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public string GoToHideoutHotkey {
            get {
                return ((string)(this["GoToHideoutHotkey"]));
            }
            set {
                this["GoToHideoutHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F10")]
        public string LogOutHotkey {
            get {
                return ((string)(this["LogOutHotkey"]));
            }
            set {
                this["LogOutHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Add")]
        public string WhisperBackHotkey {
            get {
                return ((string)(this["WhisperBackHotkey"]));
            }
            set {
                this["WhisperBackHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad0")]
        public string InviteLastPlayerHotkey {
            get {
                return ((string)(this["InviteLastPlayerHotkey"]));
            }
            set {
                this["InviteLastPlayerHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad1")]
        public string InviteFriend1Hotkey {
            get {
                return ((string)(this["InviteFriend1Hotkey"]));
            }
            set {
                this["InviteFriend1Hotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad2")]
        public string InviteFriend2Hotkey {
            get {
                return ((string)(this["InviteFriend2Hotkey"]));
            }
            set {
                this["InviteFriend2Hotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad3")]
        public string InviteFriend3Hotkey {
            get {
                return ((string)(this["InviteFriend3Hotkey"]));
            }
            set {
                this["InviteFriend3Hotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("End")]
        public string CustomHotkey {
            get {
                return ((string)(this["CustomHotkey"]));
            }
            set {
                this["CustomHotkey"] = value;
            }
        }
    }
}
